const LOGO_DESC = "purple wizard mascot with white beard wearing purple robe holding a TV remote control, glowing purple play button behind him, 'magoflix' text below in white lowercase, dark blue rounded badge";

export interface CalendarPreset {
  day: number;
  slot: "manhã" | "tarde" | "noite";
  theme: string;
  prompt: string;
  caption: string;
  aspectRatio: string;
}

export const calendarPresets: CalendarPreset[] = [
  // DIA 1
  { day: 1, slot: "manhã", theme: "Top 5 Terror", prompt: `Social media ranking card design. Dark horror-themed background with eerie fog and red lighting. Large bold title 'TOP 5 FILMES DE TERROR' in white uppercase with red glow effect. Numbers 1-5 listed vertically in large bold font. ${LOGO_DESC} badge bottom-left. Dark cinematic Instagram post card.`, caption: "😱 TOP 5 FILMES DE TERROR pra perder o sono\n\n1. O Exorcista — clássico absoluto do terror\n2. Hereditário — perturbador da década\n3. O Iluminado — Kubrick no seu melhor\n4. Invocação do Mal — baseado em fatos reais\n5. O Chamado — terror psicológico japonês\n\nQual vc já assistiu? 👇\nComenta TERROR 🎬 que eu te mando a lista completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 1, slot: "tarde", theme: "Curiosidade Cinema", prompt: `Social media fun fact card. Deep purple background with film reel and clapperboard. Bold title 'VOCÊ SABIA?' in white uppercase. ${LOGO_DESC} badge bottom-left. Trivia card design.`, caption: "🎬 VOCÊ SABIA que...\n\nO filme Titanic custou mais caro que o próprio navio Titanic quando ajustado pela inflação?\n\n💰 Filme: US$ 200 milhões (1997)\n🚢 Navio: US$ 7.5 milhões (1912) = ~US$ 180 milhões hoje\n\nHollywood é outro nível! 🤯\nComenta SABIA 🧠 pra mais curiosidades!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 1, slot: "noite", theme: "Enquete Terror vs Comédia", prompt: `Social media poll card. Split design left dark horror red, right bright yellow comedy. Bold title 'TERROR OU COMÉDIA?' in white uppercase. VS in center. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 TERROR ou COMÉDIA?\n\nSe você pudesse assistir só UM gênero pelo resto da vida, qual escolheria?\n\n😱 TERROR — adrenalina e medo\n😂 COMÉDIA — risada e diversão\n\nComenta 😱 ou 😂 nos comentários! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 2
  { day: 2, slot: "manhã", theme: "7 Séries Viciantes", prompt: `Social media ranking card design. Dark purple moody background with TV glow effect. Large bold title '7 SÉRIES QUE VICIAM' in white uppercase. Numbers 1-7 in large bold font. ${LOGO_DESC} badge bottom-left. Binge-watching theme.`, caption: "📺 7 SÉRIES que viciam desde o 1° episódio\n\n1. Breaking Bad\n2. La Casa de Papel\n3. Stranger Things\n4. The Last of Us\n5. Round 6\n6. Dark\n7. Peaky Blinders\n\nQual vc maratonou inteira? 👇\nComenta SÉRIES 📺 pra mais recomendações!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 2, slot: "tarde", theme: "Meme Maratona", prompt: `Social media meme card. Funny exhausted person on couch with popcorn everywhere. Bold title 'EU FALANDO QUE VOU DORMIR CEDO' in white uppercase. ${LOGO_DESC} badge bottom-left. Meme style card.`, caption: "😂 EU: vou dormir cedo hoje\n\nTAMBÉM EU: às 4h da manhã no 5° episódio seguido\n\nQuem nunca? 🤣\nMarca aquele amigo que faz isso SEMPRE! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 2, slot: "noite", theme: "Top 3 pra Hoje", prompt: `Social media quick pick card. Neon night theme with popcorn and remote. Bold title '3 FILMES PRA HOJE À NOITE' in white uppercase. ${LOGO_DESC} badge bottom-left.`, caption: "🌙 3 FILMES pra assistir AGORA\n\n1. Interestelar — viagem espacial épica\n2. O Poderoso Chefão — clássico eterno\n3. Matrix — ação e filosofia\n\nQual vai ser? 👇\nComenta NOITE 🎬 pra receber mais sugestões!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 3
  { day: 3, slot: "manhã", theme: "Top 5 Chorar", prompt: `Soft blue emotional background with rain drops effect. Bold title '5 FILMES PRA CHORAR' in white uppercase. ${LOGO_DESC} badge bottom-left. Tear-jerker card.`, caption: "😢 5 FILMES que vão te fazer chorar\n\n1. Marley e Eu\n2. A Culpa é das Estrelas\n3. Hachiko\n4. Diário de uma Paixão\n5. Extraordinário\n\nQual te destruiu mais? 👇\nComenta CHOREI 💔 que eu mando mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 3, slot: "tarde", theme: "Dica Streaming", prompt: `Social media tip card. Clean modern design with lightbulb icon. Bold title 'DICA DO DIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💡 DICA DO DIA\n\nSabia que no MagoFlix você pode assistir TUDO por um preço que cabe no bolso?\n\n✅ Filmes\n✅ Séries\n✅ Animes\n✅ Documentários\n\nE sem aquele preço absurdo! 🔥\nComenta PLANO 💰 pra saber mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 3, slot: "noite", theme: "Enquete Melhor Vilão", prompt: `Dark villain themed card with smoke and purple lighting. Bold title 'MELHOR VILÃO DO CINEMA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😈 Quem é o MELHOR VILÃO do cinema?\n\n1. Coringa (Heath Ledger)\n2. Thanos\n3. Darth Vader\n4. Hannibal Lecter\n5. Voldemort\n\nComenta o número do seu favorito! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 4
  { day: 4, slot: "manhã", theme: "Top 5 Ação", prompt: `Explosive orange background with fire particles. Bold title 'TOP 5 FILMES DE AÇÃO' in white with orange glow. ${LOGO_DESC} badge bottom-left. Action card.`, caption: "💥 TOP 5 FILMES DE AÇÃO\n\n1. John Wick\n2. Mad Max: Estrada da Fúria\n3. Missão Impossível\n4. Velozes e Furiosos 7\n5. Gladiador\n\nQual é o melhor? 👇\nComenta AÇÃO 🔥 pra lista completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 4, slot: "tarde", theme: "Comparativo Preço", prompt: `Price comparison card. Split design showing expensive vs affordable. Bold title 'STREAMING SEM PAGAR CARO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💸 Pra que pagar CARO em streaming?\n\nNo MagoFlix você tem TUDO por uma fração do preço:\n\n🎬 Filmes em lançamento\n📺 Séries completas\n🎌 Animes legendados\n📋 Documentários exclusivos\n\nComenta QUERO 🔥 que eu te explico!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 4, slot: "noite", theme: "Desafio Cinéfilo", prompt: `Quiz challenge card with question mark and spotlights. Bold title 'DESAFIO CINÉFILO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎯 DESAFIO CINÉFILO\n\n'Até o infinito e além!' 🚀\n\nDe qual filme é essa frase?\n\nA) Interestelar\nB) Toy Story\nC) Guardiões da Galáxia\nD) Avatar\n\nComenta a resposta! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 5
  { day: 5, slot: "manhã", theme: "Top 3 Animações", prompt: `Colorful vibrant background with magical sparkles. Bold title 'TOP 3 ANIMAÇÕES' in white. ${LOGO_DESC} badge bottom-left. Colorful card.`, caption: "✨ TOP 3 ANIMAÇÕES incríveis\n\n1. Divertida Mente 2\n2. Gato de Botas 2\n3. Elementos\n\nConcorda? 👇\nComenta ANIMAÇÃO 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 5, slot: "tarde", theme: "Fato Curioso Animação", prompt: `Fun fact card with colorful animation style background. Bold title 'FATO CURIOSO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎨 FATO CURIOSO\n\nCada frame de um filme da Pixar leva em média 24 HORAS pra renderizar!\n\nUm filme de 90 min = ~130.000 frames = ~15 ANOS de processamento contínuo!\n\nPor isso são tão perfeitos 🤩\nComenta PIXAR ✨ pra mais curiosidades!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 5, slot: "noite", theme: "Enquete Pixar vs DreamWorks", prompt: `Split comparison card. Pixar blue left, DreamWorks green right. Bold title 'PIXAR OU DREAMWORKS?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 PIXAR ou DREAMWORKS?\n\n🔵 PIXAR: Divertida Mente, Up, Toy Story\n🟢 DREAMWORKS: Shrek, Kung Fu Panda, Como Treinar seu Dragão\n\nQual estúdio é superior? Comenta! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 6
  { day: 6, slot: "manhã", theme: "5 Documentários", prompt: `Dark investigative background with spotlight. Bold title '5 DOCUMENTÁRIOS CHOCANTES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔍 5 DOCUMENTÁRIOS chocantes\n\n1. Making a Murderer\n2. The Social Dilemma\n3. Don't F**k with Cats\n4. Tiger King\n5. Seaspiracy\n\nQual te chocou? 👇\nComenta DOC 📋 pra lista completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 6, slot: "tarde", theme: "Meme Spoiler", prompt: `Meme style card with panicking person covering ears. Bold title 'QUANDO ALGUÉM DÁ SPOILER' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🚨 Quando alguém começa a falar do episódio que você NÃO VIU ainda:\n\n🙉🙉🙉\n\n'PARA PARA PARA EU NÃO VI AINDA'\n\nMarca aquele amigo que SEMPRE dá spoiler! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 6, slot: "noite", theme: "Top 3 pra Casal", prompt: `Romantic couple theme with warm lighting. Bold title '3 FILMES PRA VER A DOIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💕 3 FILMES perfeitos pra ver a dois\n\n1. Diário de uma Paixão — romance clássico\n2. La La Land — musical encantador\n3. Questão de Tempo — viagem no tempo e amor\n\nMarca seu amor! 💖👇\nComenta CASAL 💕 pra mais indicações!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 7
  { day: 7, slot: "manhã", theme: "Top 5 Comédia", prompt: `Bright yellow background with confetti. Bold title 'TOP 5 COMÉDIAS' in dark text. ${LOGO_DESC} badge bottom-left.`, caption: "😂 TOP 5 COMÉDIAS pra chorar de rir\n\n1. Se Beber Não Case\n2. As Branquelas\n3. Todo Mundo em Pânico\n4. Superbad\n5. Click\n\nQual te fez rir mais? 👇\nComenta COMÉDIA 😂 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 7, slot: "tarde", theme: "Domingo de Maratona", prompt: `Cozy weekend card with blankets and popcorn. Bold title 'DOMINGO DE MARATONA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🍿 DOMINGO DE MARATONA\n\nO plano perfeito pro domingo:\n\n☕ Manhã: café + episódio de série\n🍕 Tarde: pizza + filme de ação\n🌙 Noite: pipoca + terror\n\nQuem aí tá assim? 🙋‍♂️👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 7, slot: "noite", theme: "Ranking Vilões Marvel", prompt: `Comic book style with bold colors. Bold title 'RANKING VILÕES MARVEL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🦹 RANKING dos VILÕES MARVEL\n\n1. Thanos — o estalo que mudou tudo\n2. Killmonger — vilão com razão\n3. Loki — de vilão a herói\n4. Ultron — IA descontrolada\n5. Hela — a deusa da morte\n\nQuem é o melhor vilão? 👇\nComenta MARVEL 🦸 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 8
  { day: 8, slot: "manhã", theme: "5 Séries Coreanas", prompt: `K-drama aesthetic with pink cherry blossoms and neon Seoul. Bold title '5 SÉRIES COREANAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🇰🇷 5 SÉRIES COREANAS imperdíveis\n\n1. Round 6\n2. All of Us Are Dead\n3. Se Eu Pudesse Dizer\n4. Vincenzo\n5. Sweet Home\n\nJá assistiu? 👇\nComenta KDRAMA 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 8, slot: "tarde", theme: "K-Pop e K-Drama", prompt: `Neon Korean pop culture card. Bold title 'K-POP + K-DRAMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎵 Quem curte K-POP curte K-DRAMA!\n\nMelhores doramas com trilhas K-Pop:\n\n1. True Beauty — beleza e autoestima\n2. Goblin — fantasy romance\n3. Itaewon Class — empreendedorismo\n\nComenta KOREA 🇰🇷 pra mais indicações!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 8, slot: "noite", theme: "Enquete Dorama vs Série", prompt: `Split card Korean drama vs Western series. Bold title 'DORAMA OU SÉRIE?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 DORAMA ou SÉRIE OCIDENTAL?\n\n🇰🇷 Doramas: emoção pura, plot twists, romance\n🌍 Séries: produção épica, múltiplas temporadas\n\nQual você prefere? Comenta! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 9
  { day: 9, slot: "manhã", theme: "Top 5 Ficção Científica", prompt: `Futuristic neon cyberpunk background. Bold title 'TOP 5 FICÇÃO CIENTÍFICA' in white with neon glow. ${LOGO_DESC} badge bottom-left.`, caption: "🚀 TOP 5 FICÇÃO CIENTÍFICA\n\n1. Interestelar\n2. Matrix\n3. Blade Runner 2049\n4. A Chegada\n5. Ex Machina\n\nQual te bugou mais? 👇\nComenta FICÇÃO 🧠 pra lista completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 9, slot: "tarde", theme: "IA no Cinema", prompt: `AI themed card with circuit patterns and blue glow. Bold title 'IA NO CINEMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤖 5 FILMES sobre INTELIGÊNCIA ARTIFICIAL\n\n1. Ex Machina — IA e consciência\n2. Her — amor com uma IA\n3. Eu, Robô — rebelião das máquinas\n4. A.I. — Spielberg e a humanidade\n5. M3GAN — IA babá assustadora\n\nComenta IA 🤖 pra mais filmes!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 9, slot: "noite", theme: "Quiz Sci-Fi", prompt: `Quiz card with spaceship and stars. Bold title 'QUIZ SCI-FI' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🧪 QUIZ: Qual filme?\n\n'Houston, we have a problem' 🚀\n\nA) Gravidade\nB) Apollo 13\nC) Interestelar\nD) Perdido em Marte\n\nComenta a resposta! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 10
  { day: 10, slot: "manhã", theme: "5 Fatos Reais", prompt: `Newspaper style with typewriter elements. Bold title '5 FILMES BASEADOS EM FATOS REAIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📰 5 FILMES baseados em FATOS REAIS\n\n1. O Lobo de Wall Street\n2. À Procura da Felicidade\n3. Bohemian Rhapsody\n4. Spotlight\n5. Estrelas Além do Tempo\n\nComenta REAL 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 10, slot: "tarde", theme: "Bastidores Cinema", prompt: `Behind the scenes movie set card. Bold title 'BASTIDORES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎥 BASTIDORES que vão te surpreender\n\nNo filme Titanic, Leonardo DiCaprio improvisou a cena do desenho — não estava no roteiro!\n\nA cena ficou tão boa que o diretor manteve no corte final 🎬\n\nComenta BASTIDOR 🎥 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 10, slot: "noite", theme: "Desafio Emoji Filme", prompt: `Emoji puzzle card with colorful background. Bold title 'ADIVINHE O FILME' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎯 ADIVINHE O FILME pelos emojis!\n\n1. 🦁👑 = ?\n2. 🕷️🧑 = ?\n3. 🚢💔 = ?\n4. 🧙‍♂️💍 = ?\n5. 🦖🏝️ = ?\n\nConseguiu todos? Comenta as respostas! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 11
  { day: 11, slot: "manhã", theme: "Top 5 Romance", prompt: `Soft pink romantic background with bokeh hearts. Bold title 'TOP 5 ROMÂNTICOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💕 TOP 5 FILMES ROMÂNTICOS\n\n1. Diário de uma Paixão\n2. A Dois Metros de Você\n3. Como Eu Era Antes de Você\n4. Simplesmente Acontece\n5. Para Todos os Garotos\n\nComenta ROMANCE 💖 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 11, slot: "tarde", theme: "Casais Icônicos", prompt: `Love themed card with film strip heart shape. Bold title 'CASAIS ICÔNICOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💕 CASAIS mais ICÔNICOS do cinema\n\n1. Jack e Rose (Titanic)\n2. Noah e Allie (Diário de uma Paixão)\n3. Carl e Ellie (Up)\n4. Wall-E e Eva\n5. Shrek e Fiona\n\nQual é eterno? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 11, slot: "noite", theme: "Filme pra Chorar Hoje", prompt: `Emotional night card with moonlight. Bold title 'FILME PRA CHORAR HOJE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌙 Sugestão pra CHORAR hoje à noite:\n\n📽️ Hachiko — A Dog's Tale\n\nA história REAL do cachorro mais fiel do mundo 🐕\n\nAviso: prepare os lenços 😭\nComenta HACHI 🐕 pra mais filmes emocionantes!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 12
  { day: 12, slot: "manhã", theme: "5 Filmes Masculinos", prompt: `Dark masculine background with steel texture. Bold title '5 FILMES QUE TODO HOMEM GOSTA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔥 5 FILMES que todo HOMEM gosta\n\n1. O Poderoso Chefão\n2. Clube da Luta\n3. Tropa de Elite\n4. Os Infiltrados\n5. Gladiador\n\nMentiu se disse que não! 👇\nComenta FILMAÇO 💪 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 12, slot: "tarde", theme: "Treino + Filme", prompt: `Gym motivation card with dark tones. Bold title 'FILMES PRA TREINAR' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💪 5 FILMES que dão vontade de TREINAR\n\n1. Rocky — motivação pura\n2. Creed — a nova geração\n3. Invicto — luta por liberdade\n4. Guerreiro — MMA e família\n5. 300 — espartanos lendários\n\nComenta TREINO 💪 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 12, slot: "noite", theme: "Enquete Melhor Ator", prompt: `Awards style card with spotlight. Bold title 'MELHOR ATOR?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 Quem é o MELHOR ATOR da atualidade?\n\n1. Leonardo DiCaprio\n2. Denzel Washington\n3. Christian Bale\n4. Joaquin Phoenix\n5. Robert Downey Jr.\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 13
  { day: 13, slot: "manhã", theme: "Top 7 Suspense", prompt: `Dark noir background with venetian blind shadows. Bold title 'TOP 7 SUSPENSE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🕵️ TOP 7 FILMES DE SUSPENSE\n\n1. O Sexto Sentido\n2. Gone Girl\n3. Cisne Negro\n4. Ilha do Medo\n5. Seven\n6. O Abutre\n7. Corra!\n\nComenta SUSPENSE 🔍 pra lista completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 13, slot: "tarde", theme: "Plot Twist Real", prompt: `Mind blown card with shattered glass effect. Bold title 'PLOT TWIST DA VIDA REAL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤯 PLOT TWIST da vida real:\n\nO ator que faz o Homem de Ferro quase não conseguiu o papel!\n\nNinguém queria contratar Robert Downey Jr. — foi o diretor Jon Favreau que INSISTIU\n\nHoje ele É o Tony Stark 🫡\nComenta IRON 🤖 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 13, slot: "noite", theme: "Filme de Mistério Hoje", prompt: `Mystery night card with detective magnifying glass. Bold title 'MISTÉRIO PRA HOJE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔍 MISTÉRIO pra assistir hoje:\n\n📽️ Entre Facas e Segredos\n\nUm detetive, uma família rica e muitos suspeitos 🗡️\n\nDaniel Craig brilhando como nunca!\nComenta MISTÉRIO 🔍 pra mais thrillers!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 14
  { day: 14, slot: "manhã", theme: "5 Séries pra Maratonar", prompt: `Cozy weekend vibes with blankets and popcorn. Bold title '5 SÉRIES PRA MARATONAR NO FDS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🍿 5 SÉRIES pra MARATONAR no FDS\n\n1. The Bear\n2. Wednesday\n3. One Piece\n4. The Witcher\n5. Manifest\n\nQual vc vai começar? 👇\nComenta MARATONA 📺 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 14, slot: "tarde", theme: "Maratona Perfeita", prompt: `Cozy binge-watching setup with TV glow, blankets, popcorn and dim purple lighting. Bold title 'GUIA DA MARATONA PERFEITA' in white uppercase. ${LOGO_DESC} badge bottom-left. Streaming night card.`, caption: "📺 GUIA DA MARATONA PERFEITA no MagoFlix\n\n1️⃣ Escolhe a série (óbvio)\n2️⃣ Desliga as notificações\n3️⃣ Prepara o lanche\n4️⃣ Avisa que sumiu do mundo\n5️⃣ Assiste até não aguentar mais\n\nQuem segue esse ritual? 🙋‍♂️👇\nComenta MARATONA 🎬 pra dicas de série!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 14, slot: "noite", theme: "Trilogia Perfeita", prompt: `Epic trilogy card with three connected elements. Bold title 'MELHOR TRILOGIA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 Qual a MELHOR TRILOGIA?\n\n1. O Senhor dos Anéis\n2. O Cavaleiro das Trevas\n3. Matrix\n4. De Volta pro Futuro\n5. John Wick\n\nSó pode escolher UMA! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 15
  { day: 15, slot: "manhã", theme: "Top 5 Brasileiros", prompt: `Green and yellow Brazilian background with tropical elements. Bold title 'TOP 5 FILMES BRASILEIROS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🇧🇷 TOP 5 FILMES BRASILEIROS\n\n1. Cidade de Deus\n2. Tropa de Elite\n3. Central do Brasil\n4. O Auto da Compadecida\n5. Bacurau\n\nComenta BRASIL 🇧🇷 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 15, slot: "tarde", theme: "Cinema Nacional", prompt: `Brazilian cinema card with clapperboard and flag. Bold title 'ORGULHO NACIONAL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🇧🇷 O cinema BRASILEIRO é subestimado!\n\nSabia que Cidade de Deus foi indicado a 4 Oscars?\n\nE Central do Brasil levou Fernanda Montenegro à indicação de Melhor Atriz!\n\nValorize o cinema nacional! 🎬\nComenta BR 🇧🇷 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 15, slot: "noite", theme: "Comédias BR", prompt: `Fun Brazilian comedy card with tropical colors. Bold title 'COMÉDIAS BRASILEIRAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😂 5 COMÉDIAS BRASILEIRAS hilariantes\n\n1. O Auto da Compadecida\n2. Se Eu Fosse Você\n3. Minha Mãe é uma Peça\n4. Lisbela e o Prisioneiro\n5. Os Normais\n\nQual te fez rir mais? 👇\nComenta HUMOR 😂 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 16
  { day: 16, slot: "manhã", theme: "5 Filmes Sozinho", prompt: `Dark moody solo viewing atmosphere. Bold title '5 FILMES PRA ASSISTIR SOZINHO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌙 5 FILMES pra assistir SOZINHO\n\n1. Na Natureza Selvagem\n2. Amélie Poulain\n3. Clube da Luta\n4. Forrest Gump\n5. Soul\n\nComenta SOZINHO 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 16, slot: "tarde", theme: "Filmes Subestimados", prompt: `Hidden gem card with treasure chest. Bold title 'FILMES SUBESTIMADOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💎 5 FILMES subestimados que NINGUÉM fala\n\n1. Coração de Ferro — guerra e amizade\n2. Whiplash — obsessão pela perfeição\n3. O Grande Hotel Budapeste — arte visual\n4. Nightcrawler — jornalismo sombrio\n5. Predestinação — paradoxo insano\n\nComenta JOIA 💎 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 16, slot: "noite", theme: "Filme ou Livro?", prompt: `Book vs screen comparison card. Bold title 'FILME OU LIVRO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📚 FILME ou LIVRO — qual é melhor?\n\n1. Harry Potter — 📚 ou 🎬?\n2. O Senhor dos Anéis — 📚 ou 🎬?\n3. It — 📚 ou 🎬?\n4. Jogos Vorazes — 📚 ou 🎬?\n\nComenta sua opinião! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 17
  { day: 17, slot: "manhã", theme: "Top 5 Aventura", prompt: `Epic adventure landscape with mountains and golden light. Bold title 'TOP 5 AVENTURA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🗺️ TOP 5 FILMES DE AVENTURA\n\n1. Indiana Jones\n2. Piratas do Caribe\n3. Jurassic Park\n4. Avatar\n5. Jumanji\n\nComenta AVENTURA 🏴‍☠️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 17, slot: "tarde", theme: "Efeitos Especiais", prompt: `Before and after CGI comparison card with wireframe on one side and finished scene on the other. Bold title 'ANTES vs DEPOIS DO CGI' in white uppercase. ${LOGO_DESC} badge bottom-left. VFX breakdown card.`, caption: "🎬 ANTES vs DEPOIS do CGI\n\nVocê NÃO FAZ IDEIA de como esses filmes eram nos bastidores:\n\n1. Vingadores — tudo era tela verde 🟩\n2. Planeta dos Macacos — atores de macacão com bolinhas\n3. Avatar — só tinha o rosto dos atores de real\n4. Aquaman — piscina com fundo verde\n5. Gravidade — Sandra Bullock numa caixa\n\nQual te chocou mais? 👇\nComenta CGI 🤯 pra ver os bastidores!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 17, slot: "noite", theme: "Saga Mais Longa", prompt: `Epic saga timeline card. Bold title 'QUAL SAGA É MAIS LONGA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⏱️ Qual SAGA leva mais tempo pra assistir?\n\n1. Harry Potter — 19h 39min ⚡\n2. Senhor dos Anéis (ext.) — 11h 22min 💍\n3. Star Wars (9 filmes) — 20h 15min ⭐\n4. MCU (33 filmes) — 73h+ 🦸\n\nQual vc já maratonou inteira? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 18
  { day: 18, slot: "manhã", theme: "5 Séries de Crime", prompt: `Dark crime scene with police tape and lights. Bold title '5 SÉRIES DE CRIME' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🚨 5 SÉRIES DE CRIME viciantes\n\n1. Narcos\n2. Ozark\n3. Better Call Saul\n4. Mindhunter\n5. True Detective\n\nComenta CRIME 🔫 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 18, slot: "tarde", theme: "Máfia no Cinema", prompt: `Godfather-style mafia card with dark tones. Bold title 'MÁFIA NO CINEMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤵 5 FILMES DE MÁFIA obrigatórios\n\n1. O Poderoso Chefão — obra-prima\n2. Os Bons Companheiros — Scorsese clássico\n3. Scarface — Al Pacino lendário\n4. O Irlandês — épico de 3h30\n5. Cassino — Las Vegas e máfia\n\nComenta MÁFIA 🤵 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 18, slot: "noite", theme: "Detetive Favorito", prompt: `Detective noir card. Bold title 'MELHOR DETETIVE?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔍 Quem é o MELHOR DETETIVE da ficção?\n\n1. Sherlock Holmes\n2. Batman\n3. Benoit Blanc (Entre Facas)\n4. L (Death Note)\n5. Hercule Poirot\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 19
  { day: 19, slot: "manhã", theme: "Top 5 Super-Herói", prompt: `Comic book style with action lines. Bold title 'TOP 5 SUPER-HERÓIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🦸 TOP 5 FILMES DE SUPER-HERÓI\n\n1. Vingadores: Ultimato\n2. Cavaleiro das Trevas\n3. Homem-Aranha: Sem Volta\n4. Logan\n5. Pantera Negra\n\nComenta HERÓI 🦸 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 19, slot: "tarde", theme: "Marvel vs DC", prompt: `Split card Marvel red vs DC blue. Bold title 'MARVEL OU DC?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⚡ MARVEL ou DC?\n\n🔴 MARVEL: Vingadores, Homem-Aranha, Guardiões\n🔵 DC: Batman, Superman, Aquaman\n\nSó pode escolher UM lado! Comenta! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 19, slot: "noite", theme: "Origem do Herói", prompt: `Origin story card with dramatic transformation. Bold title 'MELHOR ORIGEM?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌟 Qual SUPER-HERÓI tem a melhor HISTÓRIA DE ORIGEM?\n\n1. Batman — trauma e vingança\n2. Homem-Aranha — responsabilidade\n3. Homem de Ferro — genialidade\n4. Thor — humildade\n5. Pantera Negra — legado\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 20
  { day: 20, slot: "manhã", theme: "5 Filmes que Bugam", prompt: `Mind-bending abstract background. Bold title '5 FILMES QUE FAZEM PENSAR' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🧠 5 FILMES que FRITAM seu cérebro\n\n1. A Origem\n2. Donnie Darko\n3. Predestinação\n4. O Show de Truman\n5. Efeito Borboleta\n\nComenta MENTE 🧠 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 20, slot: "tarde", theme: "Teoria Maluca", prompt: `Conspiracy board card with red strings. Bold title 'TEORIA MALUCA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤯 TEORIA MALUCA do cinema:\n\nE se todos os filmes da Pixar acontecem no MESMO universo?\n\nBoo (Monstros SA) = a bruxa de Valente?\nOs carros = mundo pós-humanos?\n\nFaz sentido ou viajei? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 20, slot: "noite", theme: "Filme Confuso", prompt: `Maze-like confused card. Bold title 'QUAL FILME É MAIS CONFUSO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😵 Qual filme é MAIS CONFUSO?\n\n1. Tenet — Nolan foi longe demais?\n2. Donnie Darko — ninguém entende\n3. Mulholland Drive — David Lynch surreal\n4. Primer — viagem no tempo caótica\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 21
  { day: 21, slot: "manhã", theme: "Top 5 Fantasia", prompt: `Magical fantasy background with dragons and castles. Bold title 'TOP 5 SÉRIES DE FANTASIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🐉 TOP 5 SÉRIES DE FANTASIA\n\n1. Game of Thrones\n2. The Witcher\n3. Anéis de Poder\n4. Roda do Tempo\n5. Shadow and Bone\n\nComenta FANTASIA 🧙 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 21, slot: "tarde", theme: "Mundo Mágico", prompt: `Hogwarts style magical school card. Bold title 'QUAL MUNDO MÁGICO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "✨ Em qual MUNDO MÁGICO você viveria?\n\n1. Hogwarts (Harry Potter) 🧙\n2. Terra-média (Senhor dos Anéis) 💍\n3. Nárnia 🦁\n4. Westeros (GoT) 🐉\n5. Wakanda 🏙️\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 21, slot: "noite", theme: "Dragões no Cinema", prompt: `Dragon themed card with fire breath. Bold title 'MELHORES DRAGÕES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🐉 Os MELHORES DRAGÕES do cinema e TV\n\n1. Drogon (Game of Thrones)\n2. Smaug (O Hobbit)\n3. Banguela (Como Treinar seu Dragão)\n4. Falkor (A História Sem Fim)\n5. Mushu (Mulan)\n\nQual é o mais icônico? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 22
  { day: 22, slot: "manhã", theme: "5 Filmes Família", prompt: `Warm family gathering background. Bold title '5 FILMES PRA FAMÍLIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "👨‍👩‍👧‍👦 5 FILMES pra toda FAMÍLIA\n\n1. Encanto\n2. Procurando Nemo\n3. Shrek\n4. Up: Altas Aventuras\n5. Luca\n\nComenta FAMÍLIA 🏠 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 22, slot: "tarde", theme: "Pai e Filho", prompt: `Father son bond card with warm tones. Bold title 'PAI E FILHO NO CINEMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "👨‍👦 5 Relações PAI E FILHO mais emocionantes\n\n1. À Procura da Felicidade\n2. O Rei Leão\n3. Finding Nemo\n4. Interestelar\n5. Creed\n\nQual te emociona mais? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 22, slot: "noite", theme: "Filme de Cachorro", prompt: `Cute dog themed card. Bold title 'FILMES DE CACHORRO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🐕 5 FILMES DE CACHORRO pra chorar\n\n1. Marley e Eu\n2. Hachiko\n3. Sempre ao Seu Lado\n4. A Caminho de Casa\n5. Quatro Vidas de um Cachorro\n\nComenta DOG 🐕 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 23
  { day: 23, slot: "manhã", theme: "Top 5 Guerra", prompt: `Military war-themed background with battlefield smoke. Bold title 'TOP 5 FILMES DE GUERRA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⚔️ TOP 5 FILMES DE GUERRA\n\n1. O Resgate do Soldado Ryan\n2. 1917\n3. Dunkirk\n4. Hacksaw Ridge\n5. Apocalypse Now\n\nComenta GUERRA ⚔️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 23, slot: "tarde", theme: "Heróis Reais", prompt: `Medal of honor themed card. Bold title 'HERÓIS REAIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎖️ 5 FILMES sobre HERÓIS REAIS\n\n1. Hacksaw Ridge — Desmond Doss\n2. Sully — milagre no Hudson\n3. 12 Anos de Escravidão — Solomon Northup\n4. Erin Brockovich — justiça ambiental\n5. Schindler's List — salvou 1.200 vidas\n\nComenta HERÓI 🎖️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 23, slot: "noite", theme: "Melhor Batalha", prompt: `Epic battle card with swords and shields. Bold title 'MELHOR BATALHA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⚔️ Qual BATALHA de filme é mais épica?\n\n1. Helm's Deep (Senhor dos Anéis)\n2. Wakanda (Vingadores)\n3. D-Day (Soldado Ryan)\n4. Batalha dos Bastardos (GoT)\n5. Thermopylae (300)\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 24
  { day: 24, slot: "manhã", theme: "5 Séries Curtas", prompt: `Quick-watch theme with clock elements. Bold title '5 SÉRIES CURTAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⏱️ 5 SÉRIES CURTAS pra ver em 1 dia\n\n1. Chernobyl (5 eps)\n2. The Night Of (8 eps)\n3. Bem-vindos ao Cassino (6 eps)\n4. Devs (8 eps)\n5. Bem-vindos a Wrexham (8 eps)\n\nComenta CURTA 📺 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 24, slot: "tarde", theme: "Minissérie vs Série", prompt: `Comparison card mini vs full series. Bold title 'MINISSÉRIE OU SÉRIE?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📺 MINISSÉRIE ou SÉRIE LONGA?\n\n📌 Minissérie: história completa, sem enrolação\n📌 Série longa: mais tempo com personagens queridos\n\nQual você prefere? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 24, slot: "noite", theme: "Série 1 Temporada", prompt: `One season perfection card. Bold title 'PERFEITAS EM 1 TEMPORADA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "✅ 5 SÉRIES perfeitas em UMA temporada\n\n1. Chernobyl — nota 9.4 no IMDb\n2. Band of Brothers — guerra real\n3. The Queen's Gambit — xadrez viciante\n4. Bem-vindos a Wrexham — futebol real\n5. Midnight Mass — horror atmosférico\n\nComenta UMA ✅ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 25
  { day: 25, slot: "manhã", theme: "Top 5 Anos 90", prompt: `Retro 90s aesthetic with VHS glitch. Bold title 'TOP 5 DOS ANOS 90' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📼 TOP 5 FILMES DOS ANOS 90\n\n1. Titanic\n2. Matrix\n3. Forrest Gump\n4. Pulp Fiction\n5. O Sexto Sentido\n\nComenta 90s 📼 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 25, slot: "tarde", theme: "Nostalgia 2000s", prompt: `Y2K aesthetic card with early internet vibes. Bold title 'NOSTALGIA ANOS 2000' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💿 5 FILMES dos ANOS 2000 que dão nostalgia\n\n1. Harry Potter e a Pedra Filosofal (2001)\n2. Senhor dos Anéis (2001-2003)\n3. Piratas do Caribe (2003)\n4. Batman Begins (2005)\n5. Avatar (2009)\n\nQual te dá mais nostalgia? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 25, slot: "noite", theme: "Melhor Década", prompt: `Decade comparison card. Bold title 'MELHOR DÉCADA DO CINEMA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 Qual foi a MELHOR DÉCADA do cinema?\n\n📼 Anos 80 — E.T., Star Wars, Indiana Jones\n📀 Anos 90 — Titanic, Matrix, Pulp Fiction\n💿 Anos 2000 — Senhor dos Anéis, Batman, Avatar\n📱 Anos 2010 — MCU, Interestelar, Get Out\n\nComenta a década! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 26
  { day: 26, slot: "manhã", theme: "5 True Crime", prompt: `Dark detective noir with evidence board. Bold title '5 SÉRIES TRUE CRIME' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔍 5 SÉRIES TRUE CRIME viciantes\n\n1. Making a Murderer\n2. Dahmer\n3. The Staircase\n4. Mindhunter\n5. Inventing Anna\n\nComenta CRIME 🔍 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 26, slot: "tarde", theme: "Caso Real Chocante", prompt: `True crime case file card. Bold title 'CASO REAL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📋 CASO REAL que virou série:\n\nJeffrey Dahmer — o canibal de Milwaukee\n\n🔴 17 vítimas entre 1978-1991\n🔴 Evan Peters atuou de forma assustadora\n🔴 Série mais assistida da história na categoria\n\nComenta DAHMER 📋 pra mais true crime!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 26, slot: "noite", theme: "Documentário Hoje", prompt: `Documentary tonight card. Bold title 'DOC PRA HOJE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📽️ DOCUMENTÁRIO pra assistir hoje:\n\nThe Social Dilemma 📱\n\nComo as redes sociais manipulam seu comportamento sem você perceber\n\nDepois de assistir você nunca mais vê o celular do mesmo jeito 😳\nComenta SOCIAL 📱 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 27
  { day: 27, slot: "manhã", theme: "Top 5 Natal", prompt: `Festive Christmas background with snowflakes. Bold title 'TOP 5 FILMES DE NATAL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎄 TOP 5 FILMES DE NATAL\n\n1. Esqueceram de Mim\n2. O Grinch\n3. Um Duende em Nova York\n4. Crônicas de Natal\n5. Love Actually\n\nComenta NATAL 🎅 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 27, slot: "tarde", theme: "Gênero por Humor", prompt: `Mood-based genre picker card with emoji faces representing different moods. Bold title 'GÊNERO POR HUMOR' in white uppercase. Colorful gradient background. ${LOGO_DESC} badge bottom-left.`, caption: "🎭 Qual GÊNERO assistir conforme seu HUMOR:\n\n😢 Triste → Comédia (pra dar risada)\n😤 Estressado → Animação (relaxa a mente)\n😴 Entediado → Thriller (adrenalina pura)\n🥰 Apaixonado → Romance (óbvio)\n😈 Caótico → Terror (pra sentir algo)\n\nQual é o seu humor AGORA? 👇\nComenta HUMOR 🎭 pra indicação personalizada!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 27, slot: "noite", theme: "Maratona Natal", prompt: `Christmas movie marathon card. Bold title 'MARATONA DE NATAL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎄 MARATONA DE NATAL perfeita:\n\n14h — Esqueceram de Mim 🏠\n16h — O Grinch 💚\n18h — Um Duende em Nova York 🧝\n20h — Love Actually ❤️\n22h — Crônicas de Natal 🎅\n\nQuem topa? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 28
  { day: 28, slot: "manhã", theme: "5 Animes", prompt: `Anime-style background with sakura petals. Bold title '5 ANIMES OBRIGATÓRIOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎌 5 ANIMES obrigatórios\n\n1. Attack on Titan\n2. Demon Slayer\n3. Death Note\n4. One Piece\n5. Jujutsu Kaisen\n\nComenta ANIME 🎌 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 28, slot: "tarde", theme: "Anime vs Live Action", prompt: `Split anime vs live action card. Bold title 'ANIME OU LIVE ACTION?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎌 ANIME ou LIVE ACTION?\n\nOne Piece: 🎌 Anime épico vs 🎬 Live action surpreendente\nDeath Note: 🎌 Perfeito vs 🎬 Controverso\nCowboy Bebop: 🎌 Lendário vs 🎬 Cancelado\n\nQual adaptação funcionou? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 28, slot: "noite", theme: "Personagem Anime", prompt: `Anime character card with dramatic lighting. Bold title 'PERSONAGEM FAVORITO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⚡ Qual PERSONAGEM de anime é mais forte?\n\n1. Goku (Dragon Ball)\n2. Saitama (One Punch Man)\n3. Naruto\n4. Levi (Attack on Titan)\n5. Luffy (One Piece)\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 29
  { day: 29, slot: "manhã", theme: "Top 5 Plot Twist", prompt: `Shattered glass mind-blown effect. Bold title 'TOP 5 PLOT TWISTS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤯 TOP 5 PLOT TWISTS do cinema\n\n1. O Sexto Sentido\n2. Clube da Luta\n3. Os Suspeitos\n4. A Origem\n5. O Grande Truque\n\nComenta TWIST 🤯 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 29, slot: "tarde", theme: "Final Alternativo", prompt: `Alternate ending card with forking paths. Bold title 'FINAIS ALTERNATIVOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎬 5 FILMES que quase tiveram FINAIS DIFERENTES\n\n1. Eu Sou a Lenda — final original era melhor\n2. Titanic — Rose quase divide a porta\n3. Se7en — outro pecado no final\n4. Rocky — ia perder a luta\n5. O Iluminado — cena cortada no hospital\n\nComenta FINAL 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 29, slot: "noite", theme: "Rewatch Obrigatório", prompt: `Rewatch card with play button repeat symbol. Bold title 'REWATCH OBRIGATÓRIO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔄 5 FILMES que são MELHORES no REWATCH\n\n1. A Origem — entende mais cada vez\n2. O Sexto Sentido — todos os sinais estavam lá\n3. Fight Club — detalhes escondidos\n4. Get Out — simbolismo genial\n5. Predestinação — paradoxo completo\n\nComenta REWATCH 🔄 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 30
  { day: 30, slot: "manhã", theme: "Top 10 de Todos os Tempos", prompt: `Grand cinematic background with golden award statues. Bold title 'TOP 10 DE TODOS OS TEMPOS' in white with golden glow. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 TOP 10 MELHORES FILMES\n\n1. O Poderoso Chefão\n2. Um Sonho de Liberdade\n3. Cavaleiro das Trevas\n4. Forrest Gump\n5. Matrix\n6. Interestelar\n7. Pulp Fiction\n8. Senhor dos Anéis\n9. Clube da Luta\n10. A Origem\n\nComenta FILMES 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 30, slot: "tarde", theme: "30 Dias Recap", prompt: `Celebration card with confetti and stats. Bold title '30 DIAS DE CONTEÚDO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎉 30 DIAS postando conteúdo pra vocês!\n\n📊 Números:\n🎬 90+ filmes recomendados\n📺 30+ séries indicadas\n🧠 Curiosidades diárias\n😂 Memes e enquetes\n\nO que vocês querem ver nos próximos 30 dias? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 30, slot: "noite", theme: "Votação Tema", prompt: `Vote card with ballot box. Bold title 'VOTEM NO PRÓXIMO TEMA!' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🗳️ VOTEM no tema dos próximos 30 dias!\n\n1. 🎌 Mês do Anime\n2. 🦸 Mês dos Super-Heróis\n3. 🇧🇷 Mês do Cinema Nacional\n4. 🔍 Mês do True Crime\n5. 😂 Mês da Comédia\n\nComenta o número do seu voto! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 31
  { day: 31, slot: "manhã", theme: "Top 5 Apocalipse", prompt: `Post-apocalyptic wasteland background. Bold title 'TOP 5 FILMES APOCALÍPTICOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌍 TOP 5 FILMES APOCALÍPTICOS\n\n1. Eu Sou a Lenda\n2. Mad Max: Estrada da Fúria\n3. O Dia Depois de Amanhã\n4. Zumbilândia\n5. Bird Box\n\nComenta FIM 🌍 pra lista completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 31, slot: "tarde", theme: "Sobrevivência", prompt: `Survival themed card with wilderness. Bold title 'SOBREVIVÊNCIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏕️ 5 FILMES DE SOBREVIVÊNCIA extrema\n\n1. O Regresso — DiCaprio vs urso\n2. 127 Horas — braço preso na rocha\n3. Náufrago — Wilson!\n4. Viva — acidente nos Andes\n5. Gravidade — perdida no espaço\n\nComenta SURVIVE 🏕️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 31, slot: "noite", theme: "Zumbi Favorito", prompt: `Zombie themed card with dark green tones. Bold title 'MELHOR FILME DE ZUMBI?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🧟 Qual MELHOR filme/série de ZUMBI?\n\n1. Train to Busan\n2. Zumbilândia\n3. Guerra Mundial Z\n4. The Walking Dead\n5. All of Us Are Dead\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 32
  { day: 32, slot: "manhã", theme: "Top 5 Musical", prompt: `Broadway lights and musical notes background. Bold title 'TOP 5 MUSICAIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎵 TOP 5 FILMES MUSICAIS\n\n1. La La Land\n2. O Rei do Show\n3. Bohemian Rhapsody\n4. Moulin Rouge\n5. Grease\n\nComenta MUSIC 🎵 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 32, slot: "tarde", theme: "Trilha Sonora", prompt: `Vinyl record and headphones card. Bold title 'MELHORES TRILHAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎧 5 TRILHAS SONORAS inesquecíveis\n\n1. Interestelar — Hans Zimmer 🌌\n2. O Senhor dos Anéis — Howard Shore 💍\n3. Star Wars — John Williams ⭐\n4. Inception — Hans Zimmer 🌀\n5. Gladiador — Hans Zimmer ⚔️\n\nComenta TRILHA 🎧 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 32, slot: "noite", theme: "Canta no Chuveiro", prompt: `Shower singing funny card. Bold title 'MÚSICAS DE FILME' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🚿 5 MÚSICAS DE FILME que todo mundo canta no chuveiro:\n\n1. My Heart Will Go On (Titanic)\n2. Shallow (Nasce uma Estrela)\n3. Bohemian Rhapsody\n4. Eye of the Tiger (Rocky)\n5. Stayin' Alive (Os Embalos)\n\nQual é a sua? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 33
  { day: 33, slot: "manhã", theme: "Top 5 Esporte", prompt: `Stadium sports background with dramatic lighting. Bold title 'TOP 5 FILMES DE ESPORTE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⚽ TOP 5 FILMES DE ESPORTE\n\n1. Rocky — boxe lendário\n2. Moneyball — baseball e estatística\n3. Invictus — rugby e Mandela\n4. Creed — nova geração do boxe\n5. Rush — Fórmula 1 épica\n\nComenta ESPORTE ⚽ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 33, slot: "tarde", theme: "Underdog Stories", prompt: `Underdog victory card with rising fist. Bold title 'HISTÓRIAS DE SUPERAÇÃO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💪 5 FILMES de SUPERAÇÃO que inspiram\n\n1. Rocky — nunca desistir\n2. À Procura da Felicidade — pai solo lutando\n3. Rudy — futebol americano contra tudo\n4. Karatê Kid — disciplina e coragem\n5. Whiplash — perfeição a qualquer custo\n\nComenta FORÇA 💪 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 33, slot: "noite", theme: "Melhor Cena Esportiva", prompt: `Epic sports moment card. Bold title 'MELHOR CENA ESPORTIVA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 Qual MELHOR CENA ESPORTIVA do cinema?\n\n1. Rocky vs Apollo (Rocky)\n2. Gol do Pelé (Fuga pra Vitória)\n3. Race final (Rush)\n4. Adonis vs Drago (Creed II)\n5. Treino no gelo (Miracle)\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 34
  { day: 34, slot: "manhã", theme: "Top 5 Espionagem", prompt: `Spy themed card with silhouette and laser beams. Bold title 'TOP 5 ESPIONAGEM' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🕵️ TOP 5 FILMES DE ESPIONAGEM\n\n1. James Bond: Cassino Royale\n2. Missão Impossível\n3. A Identidade Bourne\n4. Kingsman\n5. Tinker Tailor Soldier Spy\n\nComenta SPY 🕵️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 34, slot: "tarde", theme: "Melhor Espião", prompt: `Secret agent comparison card. Bold title 'MELHOR ESPIÃO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🕵️ Quem é o MELHOR ESPIÃO?\n\n1. James Bond 007\n2. Ethan Hunt (Missão Impossível)\n3. Jason Bourne\n4. Black Widow\n5. Austin Powers 😂\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 34, slot: "noite", theme: "Gadgets do Cinema", prompt: `Tech gadgets card with spy equipment. Bold title 'GADGETS DO CINEMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔧 5 GADGETS do cinema que a gente QUERIA ter:\n\n1. Sabre de Luz (Star Wars) ⚔️\n2. Manto da Invisibilidade (Harry Potter) 🧙\n3. DeLorean (De Volta pro Futuro) 🚗\n4. Traje do Homem de Ferro 🤖\n5. Neuralizer (MIB) 🕶️\n\nQual você escolheria? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 35
  { day: 35, slot: "manhã", theme: "Top 5 Distopia", prompt: `Dystopian future cityscape. Bold title 'TOP 5 DISTOPIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏚️ TOP 5 FILMES DISTÓPICOS\n\n1. Blade Runner 2049\n2. Mad Max\n3. Jogos Vorazes\n4. V de Vingança\n5. Fahrenheit 451\n\nComenta DISTOPIA 🏚️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 35, slot: "tarde", theme: "Futuro do Cinema", prompt: `Futuristic cinema card. Bold title 'FUTURO DO CINEMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔮 Como será o CINEMA em 2030?\n\n🎬 Filmes gerados por IA?\n🥽 Cinema em Realidade Virtual?\n🤖 Atores digitais?\n📱 Filmes interativos como Black Mirror?\n\nO que você acha? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 35, slot: "noite", theme: "Mundo Distópico", prompt: `Dystopian choice card. Bold title 'QUAL DISTOPIA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 Em qual MUNDO DISTÓPICO você sobreviveria?\n\n1. Jogos Vorazes — arena mortal\n2. Mad Max — deserto sem lei\n3. Matrix — simulação digital\n4. Maze Runner — labirinto\n5. Divergente — facções\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 36
  { day: 36, slot: "manhã", theme: "Top 5 Psicológico", prompt: `Psychological thriller card with distorted mirror. Bold title 'TOP 5 PSICOLÓGICO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🧠 TOP 5 FILMES PSICOLÓGICOS\n\n1. Cisne Negro\n2. O Silêncio dos Inocentes\n3. Coringa\n4. Ilha do Medo\n5. Garota Exemplar\n\nComenta PSICO 🧠 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 36, slot: "tarde", theme: "Vilão com Razão", prompt: `Sympathetic villain card. Bold title 'VILÃO COM RAZÃO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 5 VILÕES que tinham RAZÃO\n\n1. Thanos — equilíbrio universal\n2. Killmonger — justiça racial\n3. Magneto — proteção dos mutantes\n4. Coringa — sociedade falha\n5. Bane — anti-elite\n\nQual realmente tinha razão? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 36, slot: "noite", theme: "Personagem Mais Louco", prompt: `Insanity themed card with chaotic elements. Bold title 'MAIS LOUCO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😵‍💫 Qual PERSONAGEM é mais LOUCO?\n\n1. Coringa (Joaquin Phoenix)\n2. Patrick Bateman (Psicopata Americano)\n3. Tyler Durden (Clube da Luta)\n4. Hannibal Lecter\n5. Alex (Laranja Mecânica)\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 37
  { day: 37, slot: "manhã", theme: "Top 5 Viagem Tempo", prompt: `Time travel card with clock and portal. Bold title 'TOP 5 VIAGEM NO TEMPO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⏰ TOP 5 FILMES DE VIAGEM NO TEMPO\n\n1. De Volta pro Futuro\n2. Interestelar\n3. Predestinação\n4. Questão de Tempo\n5. A Chegada\n\nComenta TEMPO ⏰ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 37, slot: "tarde", theme: "Paradoxo Temporal", prompt: `Paradox themed card with infinity loop. Bold title 'PARADOXOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌀 3 PARADOXOS TEMPORAIS que bugam:\n\n1. De Volta pro Futuro — Marty quase apaga a si mesmo\n2. Predestinação — ele é ele mesmo 🤯\n3. Dark — tudo é um loop infinito\n\nQual te bugou mais? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 37, slot: "noite", theme: "Se Pudesse Voltar", prompt: `Time machine card. Bold title 'SE PUDESSE VOLTAR NO TEMPO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⏰ Se você pudesse VOLTAR NO TEMPO para assistir UM filme pela primeira vez, qual seria?\n\n1. Matrix\n2. O Sexto Sentido\n3. Vingadores: Ultimato\n4. Interestelar\n5. Clube da Luta\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 38
  { day: 38, slot: "manhã", theme: "Top 5 Vampiros", prompt: `Gothic vampire card with blood red and dark. Bold title 'TOP 5 VAMPIROS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🧛 TOP 5 FILMES/SÉRIES DE VAMPIRO\n\n1. Entrevista com o Vampiro\n2. Blade\n3. Crepúsculo (sim!)\n4. Nosferatu\n5. What We Do in the Shadows\n\nComenta VAMPIRO 🧛 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 38, slot: "tarde", theme: "Monstro Clássico", prompt: `Classic monsters card with gothic style. Bold title 'MONSTROS CLÁSSICOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "👹 Qual MONSTRO CLÁSSICO é mais assustador?\n\n1. 🧛 Drácula\n2. 🐺 Lobisomem\n3. 🧟 Zumbi\n4. 🤖 Frankenstein\n5. 👻 Múmia\n\nComenta o emoji! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 38, slot: "noite", theme: "Terror Sobrenatural", prompt: `Supernatural horror card. Bold title 'TERROR SOBRENATURAL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "👻 5 FILMES de TERROR SOBRENATURAL arrepiantes\n\n1. O Exorcista\n2. Invocação do Mal\n3. Atividade Paranormal\n4. A Profecia\n5. O Bebê de Rosemary\n\nComenta GHOST 👻 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 39
  { day: 39, slot: "manhã", theme: "Top 5 Comédia Romântica", prompt: `Light romantic comedy card with hearts and laughing. Bold title 'TOP 5 COMÉDIA ROMÂNTICA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💕😂 TOP 5 COMÉDIAS ROMÂNTICAS\n\n1. Se Eu Fosse Você\n2. Ele Não Está Tão a Fim de Você\n3. De Repente 30\n4. Um Lugar Chamado Notting Hill\n5. Legalmente Loira\n\nComenta ROMCOM 💕 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 39, slot: "tarde", theme: "Red Flag Cinema", prompt: `Red flag themed card. Bold title 'RED FLAGS DO CINEMA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🚩 5 RED FLAGS de personagens do cinema:\n\n1. Edward (Crepúsculo) — observa ela dormindo\n2. O Fantasma da Ópera — stalker musical\n3. Christian Grey — controlador\n4. Coringa — instável\n5. Anakin Skywalker — ciúmes extremo\n\nQual é a maior red flag? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 39, slot: "noite", theme: "Date Night Film", prompt: `Date night card with couple and movie screen. Bold title 'FILME PRO DATE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💑 FILME perfeito pro DATE:\n\n1° encontro: La La Land 🎶\n3° encontro: Questão de Tempo ⏰\nNamorando: Diário de uma Paixão 💕\nCasados: Se Eu Fosse Você 😂\n\nMarca aquela pessoa! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 40
  { day: 40, slot: "manhã", theme: "Top 5 Animação Adulta", prompt: `Adult animation card with mature artistic style. Bold title 'TOP 5 ANIMAÇÃO ADULTA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎨 TOP 5 ANIMAÇÕES pra ADULTOS\n\n1. Spider-Verse — visual revolucionário\n2. Akira — anime cyberpunk clássico\n3. Your Name — romance japonês lindo\n4. Valsa com Bashir — guerra animada\n5. A Viagem de Chihiro — Miyazaki genial\n\nComenta ANIMA 🎨 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 40, slot: "tarde", theme: "Studio Ghibli", prompt: `Ghibli magical card with totoro vibes. Bold title 'STUDIO GHIBLI' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌿 5 FILMES do STUDIO GHIBLI obrigatórios\n\n1. A Viagem de Chihiro\n2. Meu Amigo Totoro\n3. Princesa Mononoke\n4. O Castelo Animado\n5. O Túmulo dos Vagalumes\n\nComenta GHIBLI 🌿 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 40, slot: "noite", theme: "Melhor Animação", prompt: `Oscar animation card. Bold title 'MELHOR ANIMAÇÃO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 Qual a MELHOR ANIMAÇÃO de todos os tempos?\n\n1. Toy Story\n2. O Rei Leão\n3. Spider-Verse\n4. A Viagem de Chihiro\n5. Up: Altas Aventuras\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 41
  { day: 41, slot: "manhã", theme: "Top 5 Remake", prompt: `Before/after comparison card. Bold title 'TOP 5 REMAKES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔄 TOP 5 REMAKES que deram certo\n\n1. O Rei Leão (2019)\n2. Batman (2022)\n3. Duna (2021)\n4. IT — A Coisa (2017)\n5. Planeta dos Macacos (2011)\n\nComenta REMAKE 🔄 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 41, slot: "tarde", theme: "Remake Desnecessário", prompt: `Unnecessary card with X marks. Bold title 'REMAKES DESNECESSÁRIOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "❌ 5 REMAKES que ninguém pediu\n\n1. Mulan (live action) — cadê Mushu?\n2. A Múmia (2017) — Tom Cruise forçado\n3. Caça-Fantasmas (2016) — polêmico\n4. Ben-Hur (2016) — esquecido\n5. Point Break (2015) — sem alma\n\nConcorda? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 41, slot: "noite", theme: "Original vs Remake", prompt: `VS split card original vs remake. Bold title 'ORIGINAL OU REMAKE?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🆚 ORIGINAL ou REMAKE?\n\n1. O Rei Leão — 🎨 1994 ou 🦁 2019?\n2. IT — 🤡 1990 ou 🎈 2017?\n3. Duna — 🏜️ 1984 ou 🪐 2021?\n\nComenta ORIGINAL ou REMAKE! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 42
  { day: 42, slot: "manhã", theme: "Top 5 Diretor", prompt: `Director's chair card with clapperboard. Bold title 'TOP 5 DIRETORES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎬 TOP 5 DIRETORES do cinema\n\n1. Christopher Nolan\n2. Martin Scorsese\n3. Quentin Tarantino\n4. Steven Spielberg\n5. Denis Villeneuve\n\nComenta DIRETOR 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 42, slot: "tarde", theme: "Estilo Nolan", prompt: `Inception style card with bending city. Bold title 'UNIVERSO NOLAN' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌀 Ranking dos filmes de CHRISTOPHER NOLAN:\n\n1. Interestelar ⭐⭐⭐⭐⭐\n2. O Cavaleiro das Trevas ⭐⭐⭐⭐⭐\n3. A Origem ⭐⭐⭐⭐\n4. Dunkirk ⭐⭐⭐⭐\n5. Tenet ⭐⭐⭐\n\nConcorda? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 42, slot: "noite", theme: "Tarantino Ranking", prompt: `Retro Tarantino style card with film grain. Bold title 'RANKING TARANTINO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎬 Ranking TARANTINO:\n\n1. Pulp Fiction\n2. Django Livre\n3. Kill Bill Vol. 1\n4. Bastardos Inglórios\n5. Era Uma Vez em Hollywood\n\nQual é o melhor Tarantino? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 43
  { day: 43, slot: "manhã", theme: "Top 5 Sequência", prompt: `Sequel numbered card. Bold title 'TOP 5 SEQUÊNCIAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "2️⃣ TOP 5 SEQUÊNCIAS melhores que o original\n\n1. O Cavaleiro das Trevas > Batman Begins\n2. O Poderoso Chefão 2 > Parte 1\n3. Blade Runner 2049 > Original\n4. Divertida Mente 2 > Parte 1\n5. Aliens > Alien\n\nComenta SEQUEL 2️⃣ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 43, slot: "tarde", theme: "Sequência Ruim", prompt: `Disappointed face card. Bold title 'SEQUÊNCIAS RUINS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😤 5 SEQUÊNCIAS que decepcionaram\n\n1. Indiana Jones 4 — aliens?\n2. Matrix 3 — confuso demais\n3. Star Wars Ep. 8 — divisivo\n4. Jurassic World 3 — repetitivo\n5. Transformers 4+ — exagero\n\nQual te decepcionou mais? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 43, slot: "noite", theme: "Quer Sequência", prompt: `Wishlist card with star. Bold title 'MERECIA SEQUÊNCIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⭐ 5 FILMES que MERECEM uma sequência\n\n1. Interestelar — explorar novos planetas\n2. O Grande Truque — mais magia\n3. District 9 — o alien voltou?\n4. The Truman Show — vida pós-show\n5. Ratatouille — nova aventura culinária\n\nComenta QUERO ⭐ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 44
  { day: 44, slot: "manhã", theme: "Top 5 Terror Recente", prompt: `Modern horror card with glitch effect. Bold title 'TOP 5 TERROR RECENTE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😱 TOP 5 FILMES DE TERROR RECENTES (2020+)\n\n1. Barbarian — reviravoltas insanas\n2. Smile — sorriso perturbador\n3. Nope — Jordan Peele genial\n4. X — slasher moderno\n5. A Entidade — terror tailandês\n\nComenta MEDO 😱 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 44, slot: "tarde", theme: "Susto ou Atmosfera", prompt: `Horror comparison card. Bold title 'SUSTO OU ATMOSFERA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😱 Qual tipo de TERROR você prefere?\n\n💥 JUMP SCARE — sustos repentinos\n🌫️ ATMOSFÉRICO — tensão constante\n\nJump scare: Invocação do Mal\nAtmosférico: Hereditário\n\nComenta SUSTO ou CLIMA! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 44, slot: "noite", theme: "Filme pra Não Dormir", prompt: `Insomnia horror card. Bold title 'NÃO DORME DEPOIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌙 5 FILMES que você NÃO DORME depois:\n\n1. O Exorcista — clássico perturbador\n2. Hereditário — impossível esquecer\n3. Sinister — a fita mais sinistra\n4. Babadook — terror psicológico\n5. A Bruxa — folk horror\n\nComenta INSÔNIA 🌙 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 45
  { day: 45, slot: "manhã", theme: "Top 5 Divertidos", prompt: `Fun colorful party card. Bold title 'TOP 5 MAIS DIVERTIDOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎉 TOP 5 FILMES mais DIVERTIDOS\n\n1. Guardiões da Galáxia — humor + ação\n2. Shrek — comédia genial\n3. Deadpool — irreverente\n4. Thor: Ragnarok — hilário\n5. Jumanji — aventura e risada\n\nComenta FUN 🎉 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 45, slot: "tarde", theme: "Personagem Engraçado", prompt: `Comedy character card. Bold title 'MAIS ENGRAÇADO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😂 Qual PERSONAGEM é mais ENGRAÇADO?\n\n1. Deadpool\n2. Gênio da Lâmpada (Aladdin)\n3. Burro (Shrek)\n4. Sid (Era do Gelo)\n5. Groot\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 45, slot: "noite", theme: "Maratona Comédia", prompt: `Comedy night marathon card. Bold title 'NOITE DE COMÉDIA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😂 MARATONA de COMÉDIA perfeita:\n\n20h — Deadpool 🗡️\n22h — Se Beber Não Case 🍻\n00h — As Branquelas 💅\n02h — Todo Mundo em Pânico 😱\n\nQuem aguenta até o final? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 46
  { day: 46, slot: "manhã", theme: "Top 5 Mistério", prompt: `Mystery card with magnifying glass and clues. Bold title 'TOP 5 MISTÉRIO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔎 TOP 5 FILMES DE MISTÉRIO\n\n1. Entre Facas e Segredos\n2. Zodíaco\n3. O Código Da Vinci\n4. Mulher na Janela\n5. Whodunit\n\nComenta MISTÉRIO 🔎 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 46, slot: "tarde", theme: "Whodunit", prompt: `Detective whodunit card. Bold title 'QUEM FEZ?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🕵️ 5 filmes WHODUNIT (quem é o culpado?)\n\n1. Entre Facas e Segredos\n2. Assassinato no Expresso do Oriente\n3. Os Suspeitos\n4. Dez Pequenos Índios\n5. Scream\n\nAdivinha antes do final? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 46, slot: "noite", theme: "Detetive ou Vilão", prompt: `Choose side card. Bold title 'DETETIVE OU VILÃO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 Você seria DETETIVE ou VILÃO no cinema?\n\n🔍 Detetive: resolver crimes, buscar justiça\n😈 Vilão: planos elaborados, ninguém te para\n\nComenta DETETIVE ou VILÃO! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 47
  { day: 47, slot: "manhã", theme: "Top 5 Ficção 2024", prompt: `Modern 2024 card with futuristic elements. Bold title 'TOP 5 DE 2024' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎬 TOP 5 FILMES DE 2024 imperdíveis\n\n1. Duna: Parte 2\n2. Divertida Mente 2\n3. Deadpool & Wolverine\n4. Nosferatu\n5. The Substance\n\nQual foi o melhor? 👇\nComenta 2024 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 47, slot: "tarde", theme: "Expectativa 2025", prompt: `Coming soon card with spotlight. Bold title 'AGUARDADOS 2025' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔜 5 FILMES mais AGUARDADOS de 2025\n\n1. Vingadores: Doomsday\n2. Superman Legacy\n3. Mission Impossible 8\n4. Avatar 3\n5. Jurassic World 4\n\nQual você mais espera? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 47, slot: "noite", theme: "Oscar 2025", prompt: `Oscar award ceremony card. Bold title 'OSCAR 2025' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🏆 Quem MERECE o OSCAR de Melhor Filme?\n\n1. Anora\n2. The Brutalist\n3. Conclave\n4. Emilia Pérez\n5. Wicked\n\nComenta seu favorito! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 48
  { day: 48, slot: "manhã", theme: "Top 5 Space", prompt: `Space exploration card with stars and planets. Bold title 'TOP 5 ESPAÇO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌌 TOP 5 FILMES NO ESPAÇO\n\n1. Interestelar\n2. Gravidade\n3. Perdido em Marte\n4. Apollo 13\n5. 2001: Odisseia no Espaço\n\nComenta SPACE 🌌 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 48, slot: "tarde", theme: "Alien Favorito", prompt: `Alien themed card with UFO. Bold title 'ALIEN FAVORITO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "👽 Qual ALIEN do cinema é o mais icônico?\n\n1. Xenomorfo (Alien)\n2. E.T.\n3. Predador\n4. Neytiri (Avatar)\n5. Groot\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 48, slot: "noite", theme: "Vida em Marte", prompt: `Mars colonization card. Bold title 'MORARIA EM MARTE?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔴 Se pudesse MORAR EM MARTE como Matt Damon, você iria?\n\n✅ SIM — aventura épica, fazer história\n❌ NÃO — prefiro pizza e WiFi na Terra\n\nComenta SIM ou NÃO! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 49
  { day: 49, slot: "manhã", theme: "Top 5 Cena Icônica", prompt: `Iconic movie scene card with film strip. Bold title 'TOP 5 CENAS ICÔNICAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎬 TOP 5 CENAS mais ICÔNICAS do cinema\n\n1. 'I am your father' (Star Wars)\n2. 'Here's Johnny!' (O Iluminado)\n3. 'I'll be back' (Exterminador)\n4. Cena do restaurante (Poderoso Chefão)\n5. 'You talking to me?' (Taxi Driver)\n\nComenta ICÔNICA 🎬 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 49, slot: "tarde", theme: "Frase de Filme", prompt: `Movie quote card with speech bubble. Bold title 'FRASE MARCANTE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💬 Complete a FRASE:\n\n'Eu vou fazer uma oferta que ele não pode ___'\n\nA) recusar\nB) ignorar\nC) esquecer\nD) negar\n\nDe qual filme é? Comenta! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 49, slot: "noite", theme: "Cena de Arrepio", prompt: `Goosebumps card with chills effect. Bold title 'CENA DE ARREPIO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔥 5 CENAS que dão ARREPIO toda vez:\n\n1. Portals — Vingadores Ultimato\n2. Corrida no milharal — Interestelar\n3. Charge dos Rohirrim — Senhor dos Anéis\n4. 'I am Iron Man' — Ultimato\n5. Escada giratória — A Origem\n\nQual te arrepia? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 50
  { day: 50, slot: "manhã", theme: "Top 5 Indie", prompt: `Independent film card with film festival vibes. Bold title 'TOP 5 FILMES INDIE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎭 TOP 5 FILMES INDIE imperdíveis\n\n1. Moonlight — beleza e identidade\n2. Lady Bird — coming-of-age perfeito\n3. Whiplash — obsessão pela arte\n4. The Florida Project — infância e pobreza\n5. Everything Everywhere All at Once\n\nComenta INDIE 🎭 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 50, slot: "tarde", theme: "Filmaço Escondido", prompt: `Hidden treasure card. Bold title 'JOIAS ESCONDIDAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💎 5 FILMES INCRÍVEIS que quase ninguém viu:\n\n1. Coherence — sci-fi baixo orçamento genial\n2. The Way Back — sobrevivência WWII\n3. A Pele que Habito — Almodóvar perturbador\n4. Prisoners — thriller de Denis Villeneuve\n5. Moon — ficção sci-fi intimista\n\nComenta JOIA 💎 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 50, slot: "noite", theme: "Meio do Caminho", prompt: `Milestone celebration card. Bold title '50 DIAS!' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎉 50 DIAS de conteúdo diário!\n\n📊 Até agora:\n🎬 150+ recomendações\n📺 50+ séries\n🧠 Enquetes e curiosidades diárias\n💬 Milhares de interações\n\nObrigado por cada comentário! 💜\nFaltam 10 dias pro gran finale!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 51
  { day: 51, slot: "manhã", theme: "Top 5 Adaptação", prompt: `Book to screen card. Bold title 'TOP 5 ADAPTAÇÕES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📚 TOP 5 ADAPTAÇÕES de livro pro cinema\n\n1. O Senhor dos Anéis\n2. Harry Potter\n3. O Poderoso Chefão\n4. Clube da Luta\n5. Duna\n\nComenta LIVRO 📚 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 51, slot: "tarde", theme: "Livro vs Filme", prompt: `Book vs movie comparison. Bold title 'LIVRO VS FILME' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📖 LIVRO vs 🎬 FILME — qual ganha?\n\n1. Harry Potter — livro MUITO melhor\n2. Senhor dos Anéis — ambos perfeitos\n3. Clube da Luta — filme melhorou o livro!\n4. IT — livro mais assustador\n5. Jurassic Park — empate\n\nConcorda? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 51, slot: "noite", theme: "Quer Adaptação", prompt: `Wishlist adaptation card. Bold title 'MERECE ADAPTAÇÃO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "📚 5 LIVROS que MERECEM virar filme/série:\n\n1. A Biblioteca da Meia-Noite\n2. O Nome do Vento\n3. Sapiens\n4. 1984 (remake moderno)\n5. Percy Jackson (feito direito!)\n\nComenta ADAPTA 📚 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 52
  { day: 52, slot: "manhã", theme: "Top 5 Western", prompt: `Western card with desert and cowboy silhouette. Bold title 'TOP 5 WESTERN' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤠 TOP 5 FILMES WESTERN\n\n1. Django Livre\n2. Três Homens em Conflito\n3. Bravura Indômita\n4. Os Imperdoáveis\n5. Tombstone\n\nComenta WESTERN 🤠 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 52, slot: "tarde", theme: "Old vs New Western", prompt: `Classic vs modern western card. Bold title 'CLÁSSICO VS MODERNO' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤠 WESTERN CLÁSSICO vs MODERNO\n\n🎞️ Clássico: Três Homens em Conflito, Butch Cassidy\n🆕 Moderno: Django Livre, Hostis\n\nQual estilo você prefere? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 52, slot: "noite", theme: "Anti-Herói", prompt: `Anti-hero card with morally gray theme. Bold title 'MELHOR ANTI-HERÓI?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😎 Qual MELHOR ANTI-HERÓI?\n\n1. Deadpool\n2. Walter White\n3. Wolverine\n4. Han Solo\n5. Capitão Jack Sparrow\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 53
  { day: 53, slot: "manhã", theme: "Top 5 Catástrofe", prompt: `Disaster movie card with tsunami/volcano. Bold title 'TOP 5 CATÁSTROFE' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌋 TOP 5 FILMES DE CATÁSTROFE\n\n1. 2012\n2. O Dia Depois de Amanhã\n3. San Andreas\n4. Terremoto\n5. Greenland\n\nComenta DESASTRE 🌋 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 53, slot: "tarde", theme: "Sobreviveria?", prompt: `Survival quiz card. Bold title 'SOBREVIVERIA?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤔 Você SOBREVIVERIA a esses filmes?\n\n1. 2012 — terremoto global ✅❌\n2. Titanic — água gelada ✅❌\n3. Tubarão — mar aberto ✅❌\n4. World War Z — zumbis ✅❌\n5. Meteoro — impacto ✅❌\n\nComenta ✅ ou ❌ pra cada! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 53, slot: "noite", theme: "Pior Cenário", prompt: `Worst case scenario card. Bold title 'PIOR CENÁRIO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "😰 Qual PIOR CENÁRIO do cinema?\n\n1. 🌊 Tsunami (2012)\n2. 🧟 Apocalipse Zumbi\n3. 🤖 Rebelião das Máquinas\n4. ☄️ Asteroide (Armageddon)\n5. 👽 Invasão Alienígena\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 54
  { day: 54, slot: "manhã", theme: "Top 5 Transformação", prompt: `Before/after transformation card. Bold title 'TOP 5 TRANSFORMAÇÕES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔄 TOP 5 TRANSFORMAÇÕES de ator mais impressionantes\n\n1. Christian Bale — engordou/emagreceu 5x\n2. Charlize Theron — Monster\n3. Jared Leto — capítulo odin\n4. Robert De Niro — Touro Indomável\n5. Heath Ledger — Coringa\n\nComenta TRANSFORMA 🔄 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 54, slot: "tarde", theme: "Ator 1 Papel", prompt: `Typecasting card. Bold title 'NASCEU PRO PAPEL' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🎭 5 ATORES que NASCERAM pro papel:\n\n1. Robert Downey Jr. = Tony Stark\n2. Hugh Jackman = Wolverine\n3. Johnny Depp = Jack Sparrow\n4. Ian McKellen = Gandalf\n5. Heath Ledger = Coringa\n\nQual é impossível imaginar outro? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 54, slot: "noite", theme: "Quase Escalado", prompt: `Almost cast card with silhouettes. Bold title 'QUASE ESCALADOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🤯 5 ATORES que QUASE foram escalados:\n\n1. Will Smith quase foi Neo (Matrix)\n2. Tom Cruise quase foi Iron Man\n3. Nicolas Cage quase foi Superman\n4. Jim Carrey quase foi Jack Sparrow\n5. Al Pacino quase foi Han Solo\n\nImagina? 😱👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 55
  { day: 55, slot: "manhã", theme: "Top 5 Comida+Filme", prompt: `Food and movie pairing card. Bold title 'FILME + COMIDA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🍕 O COMBO perfeito de FILME + COMIDA:\n\n1. Terror + Pipoca 🍿😱\n2. Comédia + Pizza 🍕😂\n3. Romance + Chocolate 🍫💕\n4. Ação + Hambúrguer 🍔💥\n5. Animação + Sorvete 🍦✨\n\nQual é o seu combo? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 55, slot: "tarde", theme: "Ratatouille Real", prompt: `Gourmet cooking card. Bold title 'FILMES DE COMIDA' in white. ${LOGO_DESC} badge bottom-left.`, caption: "👨‍🍳 5 FILMES que dão FOME:\n\n1. Ratatouille — quero cozinhar!\n2. Julie & Julia — gastronomia francesa\n3. The Bear (série) — caos na cozinha\n4. Chef — food truck dos sonhos\n5. Willy Wonka — chocolate infinito\n\nComenta FOME 🍽️ pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 55, slot: "noite", theme: "Jantar com Personagem", prompt: `Dinner party card with table setting. Bold title 'JANTARIA COM QUEM?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🍽️ Com qual PERSONAGEM você JANTARIA?\n\n1. Tony Stark — papo tech\n2. Gandalf — histórias épicas\n3. Jack Sparrow — aventuras loucas\n4. Hannibal Lecter — risco 😂\n5. Shrek — diversão garantida\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 56
  { day: 56, slot: "manhã", theme: "Top 5 Coreografia", prompt: `Dance and fight choreography card. Bold title 'TOP 5 COREOGRAFIAS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "💃 TOP 5 COREOGRAFIAS épicas do cinema\n\n1. John Wick — luta perfeita\n2. Matrix — bullet time\n3. Kill Bill — espada samurai\n4. Mad Max — chase coreografada\n5. Ip Man — Wing Chun\n\nComenta LUTA 💃 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 56, slot: "tarde", theme: "Artes Marciais", prompt: `Martial arts card with fighting poses. Bold title 'ARTES MARCIAIS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🥋 5 FILMES de ARTES MARCIAIS obrigatórios\n\n1. Ip Man — Wing Chun lendário\n2. O Tigre e o Dragão — wuxia épico\n3. Ong-Bak — Tony Jaa insano\n4. Kill Bill — Tarantino + katana\n5. Karatê Kid — 'Dar cera, polir cera'\n\nComenta LUTA 🥋 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 56, slot: "noite", theme: "Lutador Favorito", prompt: `Fighter comparison card. Bold title 'MELHOR LUTADOR?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🥊 Quem vence numa luta?\n\n1. John Wick\n2. Jason Bourne\n3. Ip Man\n4. Batman\n5. Rocky\n\nComenta o número do vencedor! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 57
  { day: 57, slot: "manhã", theme: "Top 5 Trilha Sonora", prompt: `Music and cinema card with headphones and film reel, neon purple and gold. Bold title 'TOP 5 TRILHAS SONORAS' in white uppercase. ${LOGO_DESC} badge bottom-left. Cinematic music card.`, caption: "🎵 TOP 5 TRILHAS SONORAS que marcaram\n\n1. Interestelar — Hans Zimmer (arrepio puro)\n2. O Poderoso Chefão — tema icônico\n3. Star Wars — John Williams é Deus\n4. Guardiões da Galáxia — playlist perfeita\n5. Inception — BWAAAAM\n\nQual te dá arrepio? 👇\nComenta TRILHA 🎵 pra playlist completa!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 57, slot: "tarde", theme: "Mundos Fictícios", prompt: `Fantasy worlds collage with magical portals showing different fictional universes. Bold title 'MUNDOS QUE A GENTE QUERIA VIVER' in white uppercase. ${LOGO_DESC} badge bottom-left. Fantasy portal card.`, caption: "🌌 5 MUNDOS FICTÍCIOS que a gente queria visitar\n\n1. Hogwarts — quem nunca esperou a carta? ⚡\n2. Terra Média — elfos e aventura 💍\n3. Wakanda — tecnologia + cultura 🖤\n4. Pandora — natureza alien 🌿\n5. Westworld — perigoso mas tentador 🤖\n\nQual universo vc escolheria VIVER? 👇\nComenta MUNDO 🌌 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 57, slot: "noite", theme: "Tecnologia no Cinema", prompt: `Futuristic tech and cinema card with holographic displays and AI elements. Bold title 'COMO A TECNOLOGIA MUDOU O CINEMA' in white uppercase. ${LOGO_DESC} badge bottom-left. Tech evolution card.`, caption: "🤖 Como a TECNOLOGIA mudou o CINEMA\n\n1995 — Toy Story: 1ª animação 100% CGI\n2009 — Avatar: revolução do 3D\n2016 — Rogue One: ator digital (Peter Cushing)\n2019 — O Irlandês: rejuvenescimento facial\n2024 — IA gerando roteiros e storyboards\n\nO futuro do cinema é INSANO 🤯\nComenta TECH 🤖 pra mais curiosidades!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 58
  { day: 58, slot: "manhã", theme: "Top 5 Plot Holes", prompt: `Plot hole card with swiss cheese visual. Bold title 'TOP 5 PLOT HOLES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🕳️ TOP 5 PLOT HOLES famosos do cinema\n\n1. Por que os Eagles não levaram o anel? (LOTR)\n2. A porta do Titanic cabia os dois!\n3. T-Rex aparece do nada (Jurassic Park)\n4. Tempo funciona diferente (Interestelar)\n5. Ninguém reconhece o Superman de óculos\n\nQual te incomoda mais? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 58, slot: "tarde", theme: "Detalhes Escondidos", prompt: `Easter egg card with hidden details. Bold title 'DETALHES ESCONDIDOS' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🔍 5 DETALHES ESCONDIDOS em filmes famosos:\n\n1. Pizza Planet aparece em TODOS os filmes da Pixar\n2. O número A113 está em toda animação da Pixar\n3. Stan Lee em todos os filmes Marvel\n4. Starbucks no GoT (sem querer) 😂\n5. R2-D2 escondido em Star Trek\n\nSabia de algum? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 58, slot: "noite", theme: "Easter Egg", prompt: `Hidden easter egg card with magnifying glass. Bold title 'EASTER EGG FAVORITO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🥚 Qual EASTER EGG do cinema é mais legal?\n\n1. Conexões do universo Pixar\n2. Post-credits da Marvel\n3. Pizza Planet em toda Pixar\n4. Wilhelm Scream em 400+ filmes\n5. Código de números da LOST\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 59
  { day: 59, slot: "manhã", theme: "Top 5 Sci-Fi Recente", prompt: `Modern sci-fi card with neon. Bold title 'SCI-FI RECENTES' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🚀 TOP 5 SCI-FI RECENTES (2020+)\n\n1. Duna: Parte 2\n2. Everything Everywhere\n3. Nope\n4. The Creator\n5. Rebel Moon\n\nComenta SCIFI 🚀 pra mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 59, slot: "tarde", theme: "Universo Favorito", prompt: `Sci-fi universe card with multiple worlds. Bold title 'MELHOR UNIVERSO?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🌌 Em qual UNIVERSO SCI-FI você viveria?\n\n1. Star Wars — Jedi ou Sith?\n2. Star Trek — explorar galáxias\n3. Duna — deserto e poder\n4. Matrix — pílula vermelha\n5. Avatar — Pandora\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 59, slot: "noite", theme: "Poder Sci-Fi", prompt: `Superpower choice card. Bold title 'QUAL PODER?' in white. ${LOGO_DESC} badge bottom-left.`, caption: "⚡ Qual PODER do cinema você teria?\n\n1. A Força (Star Wars) ⚔️\n2. Bullet Time (Matrix) 🔫\n3. Entrar nos Sonhos (A Origem) 💭\n4. Viagem no Tempo (De Volta) ⏰\n5. Telecinese (Stranger Things) 🧠\n\nComenta o número! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 60
  { day: 60, slot: "manhã", theme: "Top 10 Final", prompt: `Grand finale golden card with confetti and trophy. Bold title 'TOP 10 DEFINITIVO' in golden text. ${LOGO_DESC} badge bottom-left. Premium celebration design.`, caption: "🏆 TOP 10 DEFINITIVO — 60 dias de conteúdo!\n\n1. Interestelar\n2. O Poderoso Chefão\n3. Cavaleiro das Trevas\n4. Pulp Fiction\n5. Matrix\n6. Senhor dos Anéis\n7. Clube da Luta\n8. Forrest Gump\n9. A Origem\n10. Parasita\n\nConcorda? Monte o seu! 👇\nComenta TOP10 🏆 pra receber recomendações!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 60, slot: "tarde", theme: "Recap 60 Dias", prompt: `Statistics celebration card with charts and confetti. Bold title '60 DIAS!' in golden text. ${LOGO_DESC} badge bottom-left. Grand celebration.`, caption: "🎉 60 DIAS DE CONTEÚDO!\n\n📊 Números incríveis:\n🎬 180 posts publicados\n📺 100+ filmes recomendados\n🎌 50+ séries indicadas\n💬 Milhares de comentários\n🧠 Enquetes e curiosidades diárias\n\nOBRIGADO por cada interação! 💜\nVocês são demais! 🔥\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 60, slot: "noite", theme: "O Que Vem Depois", prompt: `Coming next teaser card with mysterious fog. Bold title 'O QUE VEM DEPOIS?' in white with glow. ${LOGO_DESC} badge bottom-left. Suspenseful teaser design.`, caption: "🔮 O QUE VEM DEPOIS?\n\nForam 60 dias INCRÍVEIS com vocês!\n\nMas isso é só o começo... 👀\n\n📢 Novidades vindo aí:\n🎬 Reviews em vídeo\n📺 Enquetes ao vivo\n🎌 Especiais temáticos\n🏆 Sorteios exclusivos\n\nAcompanha a gente! 💜\nComenta QUERO 🔥 pra não perder nada!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 61 — Comparativo Visual de Preço
  { day: 61, slot: "manhã", theme: "Comparativo Visual Preço", prompt: `Clean modern price comparison card. Left side showing Netflix logo with R$44.90 crossed out in red, Disney+ with R$33.90 crossed out, HBO Max with R$34.90 crossed out. Right side showing MagoFlix logo with R$19.90 in green with checkmark. Bold title 'COMPARE E ECONOMIZE' in white uppercase. Dark background with purple accent. ${LOGO_DESC} badge bottom-left. Price comparison infographic style.`, caption: "💰 COMPARE E ECONOMIZE\n\n❌ Netflix: R$ 44,90/mês\n❌ Disney+: R$ 33,90/mês\n❌ HBO Max: R$ 34,90/mês\n\n✅ MagoFlix: R$ 19,90/mês — TUDO JUNTO\n\nPor que pagar mais de 100 reais se pode ter tudo por 19,90?\n\nComenta QUERO 💰 que te explico!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 61, slot: "tarde", theme: "Economia Anual", prompt: `Savings calculator card with money bills and calculator. Bold title 'QUANTO VOCÊ ECONOMIZA POR ANO?' in white. Green and purple gradient background. Big number R$1.118 in center. ${LOGO_DESC} badge bottom-left. Financial savings infographic.`, caption: "🧮 Quanto você ECONOMIZA por ano com MagoFlix?\n\nStreaming tradicional: ~R$ 113/mês = R$ 1.356/ano\nMagoFlix: R$ 19,90/mês = R$ 238/ano\n\n💰 Economia: R$ 1.118 por ANO\n\nIsso dá uma viagem de férias! ✈️\nComenta ECONOMIA 💰 pra saber mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 61, slot: "noite", theme: "CTA Direto", prompt: `Bold call-to-action card with neon QUERO button. Dark background with glowing purple/pink button in center. Bold title 'STREAMING COMPLETO POR 19,90' in white. Arrow pointing to comment area. ${LOGO_DESC} badge bottom-left. Direct CTA design.`, caption: "🔥 STREAMING COMPLETO por R$ 19,90\n\n✅ Filmes em lançamento\n✅ Séries completas\n✅ Animes legendados\n✅ Sem contrato\n✅ Cancela quando quiser\n\nQuer o link? Comenta QUERO 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 62 — Meme de Economia
  { day: 62, slot: "manhã", theme: "Meme Streaming Caro", prompt: `Meme style card showing person sweating looking at streaming bills. Bold title 'QUANDO VOCÊ VÊ O TOTAL DOS STREAMINGS' in white uppercase. Stressed face reaction. ${LOGO_DESC} badge bottom-left. Funny meme card.`, caption: "😰 Quando você vê o total dos streamings no cartão:\n\nNetflix + Disney + HBO + Prime = 150 reais/mês\n\n🤡 eu por anos\n\nAí descobre que o MagoFlix tem TUDO por 19,90\n\nMarca alguém que ainda paga caro! 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 62, slot: "tarde", theme: "Meme Cancelei", prompt: `Meme card with relaxed person on couch while chaos happens around. Bold title 'EU DEPOIS DE CANCELAR NETFLIX' in white. Peaceful face contrast. ${LOGO_DESC} badge bottom-left. Relatable meme.`, caption: "😌 EU depois de cancelar Netflix e assinar MagoFlix:\n\n- Mesmos filmes ✅\n- Mesmas séries ✅\n- Mais animes ✅\n- 19,90 no bolso ✅\n- Paz interior ✅\n\nQuem mais fez isso? 🙋‍♂️👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 62, slot: "noite", theme: "Depoimento Visual", prompt: `Testimonial card with star rating 5/5 and speech bubble. Clean dark design with purple accent. Fake user avatar. Bold title 'O QUE DIZEM SOBRE O MAGOFLIX' in white. ${LOGO_DESC} badge bottom-left. Review card design.`, caption: "⭐⭐⭐⭐⭐\n\n\"Assinei o MagoFlix faz 2 meses. Tem tudo que eu assistia antes por uma fração do preço. Melhor decisão do ano.\"\n\n— Usuário real\n\nQuer testar? Comenta TESTE 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 63 — Comparativo Visual + CTA
  { day: 63, slot: "manhã", theme: "Lado a Lado Netflix", prompt: `Side by side comparison card. Left: Netflix red with price R$44.90 and basic features. Right: MagoFlix purple with R$19.90 and ALL features checked. Bold title 'NETFLIX vs MAGOFLIX' in white. ${LOGO_DESC} badge bottom-left.`, caption: "🆚 NETFLIX vs MAGOFLIX\n\nNetflix (R$ 44,90):\n❌ Só 1 plataforma\n❌ Com anúncios no básico\n❌ Limite de telas\n\nMagoFlix (R$ 19,90):\n✅ TUDO junto\n✅ Sem anúncios\n✅ Sem limite\n\nComenta TROCA 🔄 pra saber mais!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 63, slot: "tarde", theme: "Economia Família", prompt: `Family savings card with piggy bank and family silhouette. Bold title 'ECONOMIA PRA FAMÍLIA TODA' in white. Warm purple and gold tones. ${LOGO_DESC} badge bottom-left.`, caption: "👨‍👩‍👧‍👦 ECONOMIA pra família TODA\n\nAntes: 3 streamings = R$ 130/mês\nAgora: MagoFlix = R$ 19,90/mês\n\n💰 Sobra R$ 110 por mês pra:\n🍕 Pizza no FDS\n🎮 Jogo novo\n✈️ Guardar pra viagem\n\nComenta FAMÍLIA 👨‍👩‍👧‍👦 pra saber como!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 63, slot: "noite", theme: "CTA DM Direto", prompt: `Direct message CTA card with chat bubble and arrow. Bold title 'ME CHAMA NO DM' in white with glowing effect. Dark background with neon purple chat icon. ${LOGO_DESC} badge bottom-left.`, caption: "📩 Quer streaming completo por R$ 19,90?\n\nMe chama no DM que te explico TUDO:\n\n✅ Como funciona\n✅ O que tem disponível\n✅ Como assinar\n\nSem compromisso, só informação 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  // DIA 64 — Depoimentos + Humor
  { day: 64, slot: "manhã", theme: "Review Card 2", prompt: `User review card with 4.8 rating badge. Modern clean design with avatar and verified checkmark. Bold title 'REVIEW REAL' in white. Purple gradient. ${LOGO_DESC} badge bottom-left.`, caption: "⭐ 4.8/5.0 — Review Real\n\n\"Meus filhos assistem desenho, eu assisto filme, minha esposa assiste série. Tudo por 19,90. Netflix nunca mais.\"\n\n— Pai de família satisfeito 💜\n\nComenta REVIEW ⭐ pra ver mais depoimentos!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 64, slot: "tarde", theme: "Meme Conta do Cartão", prompt: `Meme of person happily opening credit card bill. Bold title 'EU ABRINDO A FATURA DEPOIS DO MAGOFLIX' in white. Happy surprised face. ${LOGO_DESC} badge bottom-left.`, caption: "😂 EU abrindo a fatura do cartão depois de trocar pra MagoFlix:\n\nAntes: -R$ 150 em streaming 😭\nDepois: -R$ 19,90 em streaming 😎\n\nA paz que eu senti não tem preço\n\nQuem mais quer sentir isso? 👇\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
  { day: 64, slot: "noite", theme: "Preço por Dia", prompt: `Price per day breakdown card. Giant text 'R$ 0,66/DIA' in center with purple glow. Comparison to coffee price. ${LOGO_DESC} badge bottom-left.`, caption: "☕ R$ 0,66 por dia\n\nIsso é MENOS que um café!\n\nE com isso você tem:\n🎬 Filmes em lançamento\n📺 Séries completas\n🎌 Animes legendados\n📋 Documentários\n\nMagoFlix: R$ 19,90/mês\n\nComenta CAFÉ ☕ que te mando o link!\n\n@omagoflix", aspectRatio: "ASPECT_1_1" },
];

export function getCalendarInfo(index: number): { day: number; slot: string; theme: string; total: number } {
  const i = index % calendarPresets.length;
  const preset = calendarPresets[i];
  return { day: preset.day, slot: preset.slot, theme: preset.theme, total: calendarPresets.length };
}
